server:
  port: 9090
dubbo:
  application:
    name: users-sso
    qos-port: 33333
    qos-enable: true
    qos-accept-foreign-ip: false
  registry:
    address: zookeeper://112.124.202.142:2181

spring:
  redis:
    host: 112.124.202.142