server:
  port: 8080

dubbo:
  application:
    name: users-service
  registry:
    address: zookeeper://112.124.202.142:2181
  protocol:
    port: 20890


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.124.202.142:3306/cx_hd?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
