server:
  port: 8082

dubbo:
  application:
    name: navigation-service
    qos-port: 33382
    qos-enable: true
    qos-accept-foreign-ip: false
  registry:
    address: zookeeper://112.124.202.142:2181
  protocol:
    port: 20892


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.124.202.142:3306/cx_hd?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: NBshwl123!


mybatis:
  type-aliases-package: com.chuxin.pojo
  mapper-locations: classpath:mapper/*.xml