server:
  port: 9093
dubbo:
  application:
    name: ship-web
    qos-port: 33393
    qos-enable: true
    qos-accept-foreign-ip: false
  registry:
    address: zookeeper://112.124.202.142:2181

spring:
  redis:
    host: 112.124.202.142
  resources:
    static-locations: classpath:/

